import { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, StyleSheet, Text, TextInput } from "react-native";
import { useRouter } from "expo-router";
import { AccentCard, Card, Page, PrimaryButton, Screen } from "../src/components";
import { requestOtp, verifyOtp } from "../src/api";
import { colors, radii, space } from "../src/theme";

export default function LoginScreen() {
  const router = useRouter(); const [destination, setDestination] = useState(""); const [code, setCode] = useState(""); const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false);
  const send = async () => { if (!destination.trim()) return Alert.alert("Information manquante", "Saisis ton téléphone ou ton email."); setBusy(true); try { const result = await requestOtp(destination.trim()); setSent(true); if (result.devCode) { setCode(result.devCode); Alert.alert("Code de test", result.devCode); } } catch (error) { Alert.alert("Envoi impossible", error instanceof Error ? error.message : "Réessaie plus tard"); } finally { setBusy(false); } };
  const confirm = async () => { setBusy(true); try { await verifyOtp(destination.trim(), code.trim()); router.replace("/"); } catch (error) { Alert.alert("Connexion impossible", error instanceof Error ? error.message : "Code invalide"); } finally { setBusy(false); } };
  return <Screen><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : undefined}><Page><AccentCard icon="shield"><Text style={styles.kicker}>Espace sécurisé</Text><Text style={styles.title}>Bienvenue sur KayJob.</Text><Text style={styles.copy}>Connecte-toi pour commander, proposer tes compétences et suivre tes revenus.</Text></AccentCard><Card><Text style={styles.heading}>Connexion</Text><Text style={styles.label}>Téléphone ou email</Text><TextInput value={destination} onChangeText={setDestination} placeholder="+221 77 000 00 00" placeholderTextColor={colors.muted} autoCapitalize="none" style={styles.input} /><PrimaryButton label={sent ? "Renvoyer le code" : "Recevoir le code OTP"} icon="shield" onPress={send} />{sent ? <><Text style={styles.label}>Code à 6 chiffres</Text><TextInput value={code} onChangeText={setCode} placeholder="000000" placeholderTextColor={colors.muted} keyboardType="number-pad" style={styles.input} /><PrimaryButton label={busy ? "Vérification..." : "Se connecter"} icon="account" onPress={confirm} /></> : null}</Card></Page></KeyboardAvoidingView></Screen>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, kicker: { color: colors.yellow, fontWeight: "900", textTransform: "uppercase", fontSize: 12 }, title: { color: "#fff", fontSize: 29, lineHeight: 36, fontWeight: "900", marginTop: space.xs }, copy: { color: "#dfe8e4", lineHeight: 21, marginTop: space.sm }, heading: { color: colors.ink, fontSize: 22, fontWeight: "900", marginBottom: space.md }, label: { color: colors.inkSoft, fontWeight: "800", fontSize: 13, marginBottom: space.xs, marginTop: space.sm }, input: { minHeight: 52, borderWidth: 1, borderColor: colors.line, borderRadius: radii.sm, paddingHorizontal: 14, color: colors.ink, marginBottom: space.sm } });
